### ISSUE TITLE
[Tracking Issue] Update contents to kubeflow v1.5

### ISSUE THREAD

**Issue by yhwang** [IBM/KubeflowDojo#102]
Since Kubeflow v1.5 is out in April 2022, we'd like to update the content to use it. Use this issue to trace the overall progress.
- [x] Kubeflow Deployment
- [x] Kubeflow Pipelines with Tekton
- [ ] Examples, including python examples and notebooks
- [ ] KFServing to KServe

**Comment by yhwang** [comment]
- updated kubeflow deployment on #99
- updated kfp-tekton on #100

**Comment by yhwang** [comment]
update day-1 handson: #103
